#use_frameworks!
source 'https://github.com/rRun/xy_podSepcs.git'
source 'https://github.com/rocedar/RocedarPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RCFamilyDoctor_Example' do
  pod 'RCFamilyDoctor', :path => '../'

  target 'RCFamilyDoctor_Tests' do
    inherit! :search_paths

    
  end
end
